#!/bin/sh

# $Id: loadfont,v 1.4 2008-10-07 07:56:56 brian Exp $
# Copyright (c)2007 Brian Manning <brian at portaboom dot com>

# PLEASE DO NOT E-MAIL THE AUTHOR ABOUT THIS SOFTWARE
# The proper venue for questions is the LACK mailing list at:
# http://groups.google.com/linuxack or <linuxack.googlegroups.com>

if ! [ -e $LACK_FUNCTIONS ]; then
    LACK_FUNCTIONS="/etc/scripts/lack_functions.sh"
fi # if ! [ -e $LACK_FUNCTIONS ]
source $LACK_FUNCTIONS

PATH=/sbin:/bin  # No remote fs at start
ACTION=$1
BASENAME="loadfont"
DESC="'lode-lat1u-16' font from GoboLinux"

case "$ACTION" in
  vars)
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
    # purdy font
    colorize $S_TIP "${BASENAME}: Loading ${DESC};"
    $BB gunzip -c /etc/lode-lat1u-16.psf.gz | $BB loadfont
    check_exit_status $? $BASENAME
    ;;
  stop)
    # noop
    :
    ;;
  restart|force-reload)
    # noop
    :
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0
# vi: set shiftwidth=4 tabstop=4 filetype=sh :
# конец!
