#!/bin/sh

# $Id: procfs,v 1.9 2008-10-07 07:56:56 brian Exp $
# Copyright (c)2007 Brian Manning <brian at portaboom dot com>

# PLEASE DO NOT E-MAIL THE AUTHOR ABOUT THIS SOFTWARE
# The proper venue for questions is the Antlinux mailing list at:
# http://groups.google.com/linuxack or <linuxack.googlegroups.com>

# this file will get touched if we're running in debug mode; this script will
# have already been run
if [ -e /var/log/debug.env.state ]; then exit 0; fi

if ! [ -e $LACK_FUNCTIONS ]; then
    LACK_FUNCTIONS="/etc/scripts/lack_functions.sh"
fi # if ! [ -e $LACK_FUNCTIONS ]
source $LACK_FUNCTIONS
PATH=/sbin:/bin  # No remote fs at start
ACTION=$1
BINARY=/bin/mount
[ -x "$BINARY" ] || exit 1
BASENAME="procfs"
DESC="process information pseudo-filesystem (/proc)"
BINARY_OPTS="proc /proc -t proc"

# proc needs to be mounted before you can remount the root filesystem
# read/write.  Since the root filesystem is read-only at this point, when you
# mount /proc, the kernel goes to update /etc/mtab and fails (read-only
# filesystem)

case "$ACTION" in
  vars)
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
    colorize $S_TIP "$BASENAME: Mounting $DESC;"
    $BINARY $BINARY_OPTS >> $DEBUG_LOG 2>&1
    check_exit_status $? $BASENAME
    ;;
  stop)
    PATH=/bin:/sbin:/usr/bin:/usr/sbin
    colorize $S_TIP "$BASENAME: Unmounting $DESC;"
    /bin/umount /proc
    check_exit_status $? $BASENAME
    ;;
  restart|force-reload)
     $0 stop
     $0 start
    ;;
  *)
    echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0
# vi: set shiftwidth=4 tabstop=4 filetype=sh :
# конец!
