#!/bin/sh

# $Id: _initscript_stub.sh,v 1.7 2009-07-23 22:05:47 brian Exp $
# Copyright (c)2007 Brian Manning <brian at portaboom dot com>

# PLEASE DO NOT E-MAIL THE AUTHOR ABOUT THIS SOFTWARE
# The proper venue for questions is the LACK mailing list at:
# http://groups.google.com/linuxack or <linuxack.googlegroups.com>

# picks up things like colorize()
if ! [ -e $LACK_FUNCTIONS ]; then
    LACK_FUNCTIONS="/etc/scripts/lack_functions.sh"
fi # if ! [ -e $LACK_FUNCTIONS ]
source $LACK_FUNCTIONS

ACTION=$1
BINARY="/usr/sbin/switchconf"
[ -x "$BINARY" ] || exit 1
BASENAME=$(/usr/bin/basename $BINARY)
DESC="switchconf"
BINARY_OPTS=""

case "$ACTION" in
  vars)
    # echo out what commandline variables are parsed by this script
    echo "${BASENAME}:"
    exit 0
  ;;
  start)
    file_parse "/proc/cmdline" "switchconf"
    SWITCHCONF_CFG=$PARSED
    if [ "x${SWITCHCONF_CFG}" != "x" ]; then
        colorize $S_TIP \
            "${BASENAME}: Starting ${DESC} with config '${SWITCHCONF_CFG}'"
        $BINARY $SWITCHCONF_CFG >> $DEBUG_LOG 2>&1
        check_exit_status $? $BASENAME
    else
        colorize_nl $S_FAILURE \
            "${BASENAME}: 'switchconf' not set at boot prompt!"
        colorize_nl $S_FAILURE \
            "${BASENAME}: cannot run 'switchconf'"
    fi
    ;;
  stop)
    colorize $S_TIP "${BASENAME}: Stopping ${DESC}"
    ;;
  restart|force-reload)
     $0 stop
     $0 start
    ;;
  *)
    echo "Usage: $BASENAME {start|stop|restart|force-reload}" >&2
    exit 3
    ;;
esac

exit 0
# vi: set shiftwidth=4 tabstop=4 filetype=sh :
# конец!
